# Generated by Django 5.0.4 on 2024-05-19 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
